baseurl: "https://hetezen.netlify.app"
languageCode: "en-us"
title: "Heterogeneity & Zen"
theme: "hugo-ivy"
googleAnalytics: ""
disqusShortname: "hetezen"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$", "\\.draft\\.md$"]
hasCJKLanguage: true
enableEmoji: true
footnotereturnlinkcontents: "↩"
rssLimit: 100

permalinks:
  writings: "/writings/:year/:month/:slug/"
  readings: "/readings/:slug/"

menu:
  main:
    - name: "About"
      url: "/about"
      weight: 1
    - name: "Booklists"
      url: "/booklists/"
      weight: 2
    - name: "Readings"
      url: "/readings/"
      weight: 3
    - name: "Writings"
      url: "/writings/"
      weight: 4
    - name: "Tags"
      url: "/tag"
      weight: 5

params:
  description: "Heterogeneity and Zen"
  footer: "&copy; [Hetezen](/) 2022 - 2024"
  disqusURL: ""
  customJS:
    - "js/fix-toc.js"
    - "js/center-img.js"
    - "js/right-quote.js"
    - "js/no-highlight.js"
    - "js/fix-footnote.js"
    - "js/math-code.js"
    - "js/external-link.js"
    - "js/alt-title.js"
    - "js/header-link.js"
  githubContentURL: "https://github.com/hetezen/hetezen_blog/tree/master/content/"

  # options for highlight.js (version, additional languages, and theme)
  highlightjsVersion: "9.12.0"
  highlightjsCDN: "//cdnjs.cloudflare.com/ajax/libs"
  highlightjsLang: ["r", "yaml", "tex"]
  highlightjsTheme: "github"

  logo:
    en:
      img: "/images/logo3.jpg"
      url: "/"
      alt: "Hete Zen"
      tag: ""

  author:
    writings: "Hete Zen"
    booklists: "Hete Zen"

  lang:
    license:
      cn: "版权"

taxonomies:
   tag : "tags"
   category : "categories"

markup:
  defaultMarkdownHandler: Goldmark
  blackFriday:
    extensionsMask: ["noIntraEmphasis"]
    fractions: false
  goldmark:
    renderer:
      unsafe: true
