baseurl: ""
languageCode: "en-us"
title: "Heterogeneity & Zen"
theme: "hugo-ivy"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$", "\\.draft\\.md$"]
hasCJKLanguage: true
enableEmoji: true
footnotereturnlinkcontents: "↩"
rssLimit: 100

permalinks:
  cn: "/cn/:year/:month/:slug/"
  en: "/en/:year/:month/:slug/"
  readings: "/readings/:slug/"

menu:
  main:
    - name: "About"
      url: "/en/about/"
      weight: 1
    - name: "Readings"
      url: "/readings/"
      weight: 2
    - name: "Blog"
      url: "/en/"
      weight: 3
    - name: "日志"
      url: "/cn/"
      weight: 4

  en:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "About"
      url: "/en/about/"
      weight: 2
    - name: "Readings"
      url: "/readings/"
      weight: 3
    - name: "Blog"
      url: "/en/"
      weight: 4
    - name: "Tags"
      label: "tags"
      url: "/tags/"
      weight: 5
    - name: "中文"
      url: "/cn/"
      weight: 6
  cn:
    - name: "首页"
      url: "/"
      weight: 1
    - name: "关于"
      url: "/en/about/"
      weight: 2
    - name: "读书"
      url: "/readings/"
      weight: 3
    - name: "博客"
      url: "/cn/"
      weight: 4
    - name: "Tags"
      label: "tags"
      url: "/tags/"
      weight: 5
    - name: "English"
      url: "/en/"
      weight: 6

params:
  description: "Heterogeneity and Zen"
  footer: "&copy; [Hetezen](/) 2022 - 2022"
  disqusURL: ""
  customJS:
    - "fix-toc.js"
    - "center-img.js"
    - "right-quote.js"
    - "no-highlight.js"
    - "fix-footnote.js"
    - "math-code.js"
    - "hash-notes.js"
    - "toggle-notes.js"
    - "post-nav.js"
    - "external-link.js"
    - "alt-title.js"
  githubContentURL: "https://github.com/hetezen/hetezen_blog/tree/master/content/"

  # options for highlight.js (version, additional languages, and theme)
  highlightjsVersion: "9.12.0"
  highlightjsCDN: "//cdnjs.cloudflare.com/ajax/libs"
  highlightjsLang: ["r", "yaml", "tex"]
  highlightjsTheme: "github"

  logo:
    en:
      img: "/images/logo3.jpg"
      url: "/"
      alt: "Hete Zen"
      tag: ""

  author:
    en: "Hete Zen"
    cn: "Hete Zen"

  lang:
    edit:
      cn: "编辑"
    license:
      cn: "版权"
    subscribe:
      cn: "订阅"

taxonomies:
   tag : "tags"
   category : "categories"

markup:
  defaultMarkdownHandler: Goldmark
  blackFriday:
    extensionsMask: ["noIntraEmphasis"]
    fractions: false
  goldmark:
    renderer:
      unsafe: true
